### ISSUE TITLE
Evaluate Auth Approval Form

### ISSUE THREAD

**Issue by wesleyboar** [tapis-project/authenticator#48]
## Overview

The token auth approval after login is unexpected for Core Portal user. Is it necessary? If so, then why so many steps (checkbox and button)?

To submit login, and then be asked to do more, is confusing. In typical user interfaces, after username and password are accepted, login is complete. But at TAPIS, it is apparently not.

<details>

As a user, if I enter my username and password, and press login, I want to login. If a token is required to do that, why does user care? If user does not approve, then they cannot login. And they only submitted login form in order to login. And after submission, think they are done, yet they are not.

</details>

Please help me understand. There may be a way to simplify this user experience, but I am not confident to propose changes until I understand the reason for the current experience.

| prod. | dev. |
| - | - |
| <img width="765" alt="authorize prod" src="https://github.com/tapis-project/authenticator/assets/62723358/86269e0c-ab2d-4ae0-b585-7ffbf2bdae63"> | <img width="647" alt="authorize dev" src="https://github.com/tapis-project/authenticator/assets/62723358/665d39c2-6f9f-45b2-a474-705a635550f4"> |

## 🆕 Proposal

**Add the branding at the top of the form** (to increase trust) **and** change layout to:

| `{% if device_code %}` | no `device_code` |
| - | - |
| <img width="660" alt="has device" src="https://github.com/tapis-project/authenticator/assets/62723358/511e5eb7-65f3-4114-bbb3-eab8b3a180f4"> | <img width="660" alt="no device" src="https://github.com/tapis-project/authenticator/assets/62723358/8dc5f5fa-2426-4672-b4ef-196ee1e0be9d"> |

**Comment by wesleyboar** [comment]
I see now a conditional TTL field "Time for token to live in days (default: 30)". If that field is present, then I understand how this became a separate form. Without the field, the user experience is still unexpected.

**Comment by wesleyboar** [comment]
Even with the TTL field, I support C.J.'s ([private](https://tacc-team.slack.com/archives/G01K9ET7JM7/p1693602848802539)) suggestion to change:
* from **[✓] Approve** and **[ Submit ]**
* to just <del>**[ Approve ]**</del> <ins>**[ Authorize ]**</ins>

**Comment by wesleyboar** [comment]
In #49, I propose:
- fix to layout bug with TTL and [✓] Approve
- new style for the TTL field

**Comment by joestubbs** [comment]
In general, I am very much in favor of simplifying the flow whenever we can. Specifically, the proposal to remove/combine the Approve box and Submit button into 1 input makes sense. 

One thing to keep in mind is that the authorize/approval screen function is somewhat orthogonal to user authentication; once the user authenticates, they have an active session which can live on for hours or days, and during that time they can be shown multiple "authorize" screens because this screen is shown per client application. The idea is that the user is authorizing (or approving) a third-party application to take actions on their behalf. The client application could be the main DesignSafe portal or the SimCenter app, or it could even be a CLI or notebook application they are running on their own machine. So in general, we do need the authorize screen (and it is part of the OAuth spec).

With that said, we have discussed the possibility of adding an "approve always" option, so that a user only can essentially authorize a specific client app once for all time. That's a new feature in the app though and will take some coding to implement, but it is on the list.

**Comment by wesleyboar** [comment]
@joestubbs Your reply is very helpful. I think I get it now.[^1] It's similar to authorizing GitHub to connect to a client application, but multiple apps share the authorization. Since your response, Craig and I mocked up a proposed layout (below). Do you have any concerns with it?

<img width="645" alt="auth form" src="https://github.com/tapis-project/authenticator/assets/62723358/f343e945-d100-45e9-894b-c4bfe144e235">

[^1]: My scope of understanding of Tapis UI had been isolated to Core Portals usage, but now I see Tapis has features for clients with different authorization needs.

**Comment by joestubbs** [comment]
@wesleyboar the design looks beautiful! Thanks SO much

**Comment by wesleyboar** [comment]
New text was offered to internal stakeholders. ([Internal reference.](https://tacc-team.slack.com/archives/C05UDEE99M5/p1696279563531499)) PR #49 implements the text chosen by the majority.
